development:
  adapter: redis
  url: <%= ENV["REDIS_URL"] %>
  channel_prefix: picture_application_development

test:
  adapter: test

production:
  adapter: redis
  url: <%= ENV["REDIS_URL"] %>
  channel_prefix: picture_application_production
