# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d42bc0efa3014faf6eea6038519f34b2277ff401a033e835d14006304ff48f0f031e03a87a2a88c5ee34ce05c475a29ea3ce6b79b79a826348d6ac9da6f2f95a

test:
  secret_key_base: fc6e3ba6c6de4e1147c0911c6d849bd5918b6a82e04e1edd293267d622ff3a7720585cfafaafddfae9f61aee3c9dec3db639179b86f1496f21cadaee2fa64e99

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
